# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  enabled: true
  host: localhost
  port: 3035

development:
  <<: *default

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
