---
openapi: 3.0.3
info:
  title: WhatsOpt API
  version: v1
  contact:
    name: API Support
    email: remi.lafage@onera.fr
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://ether.onera.fr/whatsopt
  description: External production server
- url: https://selene.onecert.fr/whatsopt
  description: Internal production server
- url: https://erebe.onecert.fr/whatsopt
  description: Internal Restricted server
- url: https://selene.onecert.fr/whatsopt-dev
  description: Internal staging server
- url: http://erebe.onecert.fr:3000
  description: Development server
paths:
  "/api/v1/analyses":
    get:
      summary: Get analyses
      tags:
      - Multi-Disciplinary Analyses
      security:
      - Token: []
      responses:
        '200':
          description: List analyses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
  "/api/v1/analyses/{id}":
    get:
      summary: Get analysis details
      tags:
      - Multi-Disciplinary Analyses
      security:
      - Token: []
      parameters:
      - name: id
        in: path
        description: Analysis identifier
        required: true
        schema:
          type: string
      responses:
        '200':
          description: return analysis information
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AnalysisInfo"
  "/api/v1/analyses/{id}.xdsm":
    get:
      summary: Get XDSMjs format for given analysis
      tags:
      - Multi-Disciplinary Analyses
      security:
      - Token: []
      parameters:
      - name: id
        in: path
        description: Analysis identifier
        required: true
        schema:
          type: string
      responses:
        '200':
          description: return XDSM structure
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Xdsm"
components:
  schemas:
    AnalysisInfo:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        owner_email:
          type: string
          format: email
        notes:
          type: string

    Xdsm:
      type: object
      additionalProperties:
        type: object
        properties:
          nodes:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                type:
                  type: string
          edges:
            type: array
            items:
              type: object
              properties:
                from:
                  type: string
                to:
                  type: string
                name:
                  type: string

  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your API key with the format **Token &lt;API key&gt;**
security:
- Token: []
tags:
- name: Multi-Disciplinary Analyses
  description: Operations for using analyses created in WhatsOpt
externalDocs:
  description: Find out more on WhatsOpt
  url: http://github.com/OneraHub/WhatsOpt
